// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCATCHJiNUri02ldZL0MaNACQ82ddWu6_Q',
    appId: '1:175571916693:android:50793d065eaf664caa489c',
    messagingSenderId: '175571916693',
    projectId: 'timebachaodev',
    storageBucket: 'timebachaodev.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvdG7yPM_KMxqnpSRHa-Fhfpwj0ArsNHo',
    appId: '1:175571916693:web:e2b6df8a8469d9a8aa489c',
    messagingSenderId: '175571916693',
    projectId: 'timebachaodev',
    authDomain: 'timebachaodev.firebaseapp.com',
    storageBucket: 'timebachaodev.firebasestorage.app',
    measurementId: 'G-N18K4TX69B',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt_f-Bhx0NPh6aOlxf9jGHpFhGHE_6G8Q',
    appId: '1:175571916693:ios:d884c0f91666ee37aa489c',
    messagingSenderId: '175571916693',
    projectId: 'timebachaodev',
    storageBucket: 'timebachaodev.firebasestorage.app',
    iosBundleId: 'com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvdG7yPM_KMxqnpSRHa-Fhfpwj0ArsNHo',
    appId: '1:175571916693:web:189da83fd33cdbb5aa489c',
    messagingSenderId: '175571916693',
    projectId: 'timebachaodev',
    authDomain: 'timebachaodev.firebaseapp.com',
    storageBucket: 'timebachaodev.firebasestorage.app',
    measurementId: 'G-LBSS3DVZ4D',
  );

}