// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfcdvW8PB0aRhnEgXD7C6cU1YWadkgnc',
    appId: '1:207691663784:android:fcf699ea91d12f0488b59d',
    messagingSenderId: '207691663784',
    projectId: 'timebachaodev-9a8aa',
    storageBucket: 'timebachaodev-9a8aa.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtHhiqPWsA5Bk7yvKu-VNCsqhXMe27Wwc',
    appId: '1:207691663784:web:855333bb446a1a6388b59d',
    messagingSenderId: '207691663784',
    projectId: 'timebachaodev-9a8aa',
    authDomain: 'timebachaodev-9a8aa.firebaseapp.com',
    storageBucket: 'timebachaodev-9a8aa.firebasestorage.app',
    measurementId: 'G-PFDQ3YZ2WL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_yOxL0YfcBs30jwnbdde0Dcvf-gtTdAw',
    appId: '1:207691663784:ios:dd12d6cf78788ecc88b59d',
    messagingSenderId: '207691663784',
    projectId: 'timebachaodev-9a8aa',
    storageBucket: 'timebachaodev-9a8aa.firebasestorage.app',
    iosBundleId: 'com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtHhiqPWsA5Bk7yvKu-VNCsqhXMe27Wwc',
    appId: '1:207691663784:web:b6adef4fa6f0a0f188b59d',
    messagingSenderId: '207691663784',
    projectId: 'timebachaodev-9a8aa',
    authDomain: 'timebachaodev-9a8aa.firebaseapp.com',
    storageBucket: 'timebachaodev-9a8aa.firebasestorage.app',
    measurementId: 'G-G5H3N9CTWZ',
  );

}